In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
        

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv

In [3]:
df = pd.read_csv('/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [7]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [8]:
df.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True)

In [9]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [10]:
df = pd.get_dummies(df, columns=['Geography', 'Gender'], drop_first=True, dtype=int)

In [11]:
X = df.drop(columns=['Exited'])
y = df['Exited']

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [13]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [14]:
X_train.shape

(8000, 11)

In [15]:
y_train.shape

(8000,)

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)

In [17]:
X_train_scale

array([[-0.23082038, -0.94449979, -0.70174202, ...,  1.71490137,
        -0.57273139,  0.91509065],
       [-0.25150912, -0.94449979, -0.35520275, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [-0.3963303 ,  0.77498705,  0.33787579, ...,  1.71490137,
        -0.57273139, -1.09278791],
       ...,
       [ 0.22433188,  0.58393295,  1.3774936 , ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 0.13123255,  0.01077067,  1.03095433, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 1.1656695 ,  0.29735181,  0.33787579, ...,  1.71490137,
        -0.57273139,  0.91509065]])

In [18]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

2026-05-12 15:19:40.246863: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1778599180.573050      57 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1778599180.666812      57 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1778599181.465878      57 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1778599181.465933      57 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1778599181.465935      57 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1778599181.465937      57 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

In [19]:
model = Sequential()

model.add(Dense(7,activation='relu',input_dim=11))
model.add(Dense(7,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2026-05-12 15:20:15.038493: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

In [20]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 7)              │            84 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 7)              │            56 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             8 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 148 (592.00 B)

 Trainable params: 148 (592.00 B)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [22]:
history = model.fit(X_train_scale,y_train,epochs=100,validation_split=0.2)

Epoch 1/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.4575 - loss: 0.7349 - val_accuracy: 0.8006 - val_loss: 0.5210
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7947 - loss: 0.5027 - val_accuracy: 0.8050 - val_loss: 0.4513
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8049 - loss: 0.4487 - val_accuracy: 0.8163 - val_loss: 0.4343
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8207 - loss: 0.4200 - val_accuracy: 0.8138 - val_loss: 0.4265
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8235 - loss: 0.4190 - val_accuracy: 0.8213 - val_loss: 0.4209
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8278 - loss: 0.4084 - val_accuracy: 0.8213 - val_loss: 0.4145
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8287 - loss: 0.4100 - val_accuracy: 0.8219 - val_loss: 0.4084
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8254 - loss: 0.4095 - val_accuracy: 0.8256 - val_loss: 0.4028
Epoch 9/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8289 - loss: 0.3980 - val_accuracy: 0.8238 - val_loss: 0.3983
Epoch 10/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8336 - loss: 0.3909 - val_accuracy: 0.8256 - val_loss: 0.3941
Epoch 11/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8243 - loss: 0.4077 - val_accuracy: 0.8300 - val_loss: 0.3890
Epoch 12/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8385 - loss: 0.3845 - val_accuracy: 0.8356 - val_loss: 0.3842
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8370 - loss: 0.3817 - val_accuracy: 0.8388 - val_loss: 0.3800
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8429 - loss: 0.3777 - val_accuracy: 0.8356 - val_loss: 0.3772
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8486 - loss: 0.3712 - val_accuracy: 0.8381 - val_loss: 0.3740
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8387 - loss: 0.3774 - val_accuracy: 0.8381 - val_loss: 0.3705
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8477 - loss: 0.3650 - val_accuracy: 0.8413 - val_loss: 0.3672
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8449 - loss: 0.3739 - val_accuracy: 0.8431 - val_loss: 0.3664
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8503 - loss: 0.3510 - val_accuracy: 0.8413 - val_loss: 0.3624
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8493 - loss: 0.3643 - val_accuracy: 0.8425 - val_loss: 0.3642
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8548 - loss: 0.3486 - val_accuracy: 0.8444 - val_loss: 0.3594
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8437 - loss: 0.3671 - val_accuracy: 0.8475 - val_loss: 0.3574
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8538 - loss: 0.3490 - val_accuracy: 0.8475 - val_loss: 0.3537
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8519 - loss: 0.3557 - val_accuracy: 0.8469 - val_loss: 0.3533
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8576 - loss: 0.3518 - val_accuracy: 0.8500 - val_loss: 0.3516
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8586 - loss: 0.3584 - val_accuracy: 0.8462 - val_loss: 0.3538
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8596 - loss: 0.3467 - val_accuracy: 0.8512 - val_loss: 0.3509
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8512 - loss: 0.3583 - val_accuracy: 0.8525 - val_loss: 0.3482
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8663 - loss: 0.3260 - val_accuracy: 0.8544 - val_loss: 0.3482
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8646 - loss: 0.3347 - val_accuracy: 0.8525 - val_loss: 0.3482
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8675 - loss: 0.3324 - val_accuracy: 0.8556 - val_loss: 0.3466
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8612 - loss: 0.3383 - val_accuracy: 0.8544 - val_loss: 0.3468
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8647 - loss: 0.3352 - val_accuracy: 0.8544 - val_loss: 0.3449
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8692 - loss: 0.3248 - val_accuracy: 0.8550 - val_loss: 0.3456
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8674 - loss: 0.3351 - val_accuracy: 0.8569 - val_loss: 0.3441
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8591 - loss: 0.3429 - val_accuracy: 0.8550 - val_loss: 0.3439
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8679 - loss: 0.3267 - val_accuracy: 0.8569 - val_loss: 0.3446
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8732 - loss: 0.3286 - val_accuracy: 0.8556 - val_loss: 0.3451
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8649 - loss: 0.3291 - val_accuracy: 0.8594 - val_loss: 0.3440
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8660 - loss: 0.3318 - val_accuracy: 0.8556 - val_loss: 0.3429
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8604 - loss: 0.3372 - val_accuracy: 0.8562 - val_loss: 0.3418
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8688 - loss: 0.3230 - val_accuracy: 0.8537 - val_loss: 0.3427
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8647 - loss: 0.3311 - val_accuracy: 0.8500 - val_loss: 0.3452
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8577 - loss: 0.3473 - val_accuracy: 0.8569 - val_loss: 0.3423
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8542 - loss: 0.3495 - val_accuracy: 0.8556 - val_loss: 0.3420
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8723 - loss: 0.3206 - val_accuracy: 0.8550 - val_loss: 0.3427
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8686 - loss: 0.3315 - val_accuracy: 0.8537 - val_loss: 0.3429
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8699 - loss: 0.3272 - val_accuracy: 0.8544 - val_loss: 0.3415
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8731 - loss: 0.3183 - val_accuracy: 0.8519 - val_loss: 0.3419
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8640 - loss: 0.3383 - val_accuracy: 0.8500 - val_loss: 0.3439
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8723 - loss: 0.3229 - val_accuracy: 0.8569 - val_loss: 0.3419
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8651 - loss: 0.3358 - val_accuracy: 0.8500 - val_loss: 0.3439
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8622 - loss: 0.3322 - val_accuracy: 0.8500 - val_loss: 0.3430
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8698 - loss: 0.3273 - val_accuracy: 0.8556 - val_loss: 0.3405
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8662 - loss: 0.3374 - val_accuracy: 0.8525 - val_loss: 0.3408
Epoch 56/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8678 - loss: 0.3349 - val_accuracy: 0.8531 - val_loss: 0.3433
Epoch 57/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8573 - loss: 0.3422 - val_accuracy: 0.8494 - val_loss: 0.3423
Epoch 58/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8724 - loss: 0.3231 - val_accuracy: 0.8506 - val_loss: 0.3420
Epoch 59/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8573 - loss: 0.3374 - val_accuracy: 0.8512 - val_loss: 0.3430
Epoch 60/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8721 - loss: 0.3254 - val_accuracy: 0.8500 - val_loss: 0.3434
Epoch 61/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8698 - loss: 0.3216 - val_accuracy: 0.8525 - val_loss: 0.3407
Epoch 62/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8680 - loss: 0.3250 - val_accuracy: 0.8512 - val_loss: 0.3435
Epoch 63/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8619 - loss: 0.3391 - val_accuracy: 0.8487 - val_loss: 0.3437
Epoch 64/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8691 - loss: 0.3300 - val_accuracy: 0.8562 - val_loss: 0.3424
Epoch 65/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8559 - loss: 0.3469 - val_accuracy: 0.8531 - val_loss: 0.3429
Epoch 66/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8636 - loss: 0.3265 - val_accuracy: 0.8494 - val_loss: 0.3434
Epoch 67/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8737 - loss: 0.3164 - val_accuracy: 0.8506 - val_loss: 0.3430
Epoch 68/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8668 - loss: 0.3282 - val_accuracy: 0.8487 - val_loss: 0.3438
Epoch 69/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8637 - loss: 0.3337 - val_accuracy: 0.8500 - val_loss: 0.3449
Epoch 70/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8706 - loss: 0.3218 - val_accuracy: 0.8525 - val_loss: 0.3428
Epoch 71/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8687 - loss: 0.3368 - val_accuracy: 0.8494 - val_loss: 0.3444
Epoch 72/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8629 - loss: 0.3255 - val_accuracy: 0.8525 - val_loss: 0.3457
Epoch 73/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8707 - loss: 0.3145 - val_accuracy: 0.8525 - val_loss: 0.3442
Epoch 74/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8682 - loss: 0.3274 - val_accuracy: 0.8506 - val_loss: 0.3438
Epoch 75/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8627 - loss: 0.3369 - val_accuracy: 0.8487 - val_loss: 0.3457
Epoch 76/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8735 - loss: 0.3173 - val_accuracy: 0.8531 - val_loss: 0.3441
Epoch 77/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8654 - loss: 0.3310 - val_accuracy: 0.8512 - val_loss: 0.3432
Epoch 78/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8686 - loss: 0.3290 - val_accuracy: 0.8519 - val_loss: 0.3435
Epoch 79/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8694 - loss: 0.3257 - val_accuracy: 0.8500 - val_loss: 0.3449
Epoch 80/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8691 - loss: 0.3282 - val_accuracy: 0.8512 - val_loss: 0.3434
Epoch 81/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8666 - loss: 0.3372 - val_accuracy: 0.8519 - val_loss: 0.3449
Epoch 82/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8732 - loss: 0.3267 - val_accuracy: 0.8537 - val_loss: 0.3431
Epoch 83/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8641 - loss: 0.3426 - val_accuracy: 0.8525 - val_loss: 0.3442
Epoch 84/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8676 - loss: 0.3358 - val_accuracy: 0.8537 - val_loss: 0.3470
Epoch 85/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8724 - loss: 0.3232 - val_accuracy: 0.8494 - val_loss: 0.3471
Epoch 86/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8701 - loss: 0.3254 - val_accuracy: 0.8519 - val_loss: 0.3446
Epoch 87/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8684 - loss: 0.3220 - val_accuracy: 0.8537 - val_loss: 0.3448
Epoch 88/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8666 - loss: 0.3295 - val_accuracy: 0.8550 - val_loss: 0.3421
Epoch 89/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8657 - loss: 0.3298 - val_accuracy: 0.8512 - val_loss: 0.3416
Epoch 90/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8700 - loss: 0.3190 - val_accuracy: 0.8562 - val_loss: 0.3429
Epoch 91/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8719 - loss: 0.3185 - val_accuracy: 0.8556 - val_loss: 0.3422
Epoch 92/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8624 - loss: 0.3367 - val_accuracy: 0.8550 - val_loss: 0.3437
Epoch 93/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8660 - loss: 0.3312 - val_accuracy: 0.8500 - val_loss: 0.3428
Epoch 94/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8658 - loss: 0.3326 - val_accuracy: 0.8519 - val_loss: 0.3447
Epoch 95/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8683 - loss: 0.3299 - val_accuracy: 0.8537 - val_loss: 0.3442
Epoch 96/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8637 - loss: 0.3309 - val_accuracy: 0.8544 - val_loss: 0.3433
Epoch 97/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8709 - loss: 0.3128 - val_accuracy: 0.8569 - val_loss: 0.3431
Epoch 98/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8688 - loss: 0.3228 - val_accuracy: 0.8519 - val_loss: 0.3436
Epoch 99/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8707 - loss: 0.3187 - val_accuracy: 0.8581 - val_loss: 0.3425
Epoch 100/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8673 - loss: 0.3341 - val_accuracy: 0.8531 - val_loss: 0.3435

In [23]:
model.layers[0].get_weights()

[array([[ 9.1920525e-02,  1.4811607e-01, -4.1916347e-01,  1.4726552e-01,
          1.5852118e-01, -1.2748295e-01,  5.7912271e-02],
        [-3.1080809e-01, -4.8628550e-02,  5.1452726e-01, -8.8239789e-01,
         -3.7471101e-02, -4.4801739e-01,  8.4969807e-01],
        [-2.2631375e-02,  6.6480793e-02, -3.2939887e-01, -2.8109828e-02,
          1.8808257e-03, -1.3996403e-01,  3.1169781e-01],
        [-3.7758768e-01, -8.8182288e-01, -1.7256397e-01, -1.1710531e-01,
          2.1794239e-01,  2.2266385e-01, -2.8257564e-01],
        [-1.4737611e+00, -7.0860583e-01, -1.2937769e-01, -9.0850092e-02,
          1.0849826e+00, -2.6541102e-01,  1.7185687e-01],
        [-6.1233290e-02, -2.4129653e-01,  9.1271438e-02, -1.8281810e-02,
          5.5960134e-02,  8.4483966e-02,  3.9829120e-01],
        [-5.5433166e-01,  2.3768727e-02,  4.2493697e-02, -4.0443093e-01,
         -6.6825861e-01, -4.9370337e-01,  6.0862690e-01],
        [ 6.5759756e-02,  4.8039623e-02, -2.8411010e-01,  7.0176356e-02,
          5.2618150e-02, -9.3688577e-02,  1.7610472e-02],
        [ 1.6283855e-01, -3.0955452e-01,  1.8015030e-01,  2.9610809e-02,
         -3.6619820e-02,  1.2170839e-01, -2.5551869e-02],
        [-9.4475865e-02, -8.1120297e-02,  2.7360640e-02,  7.0482068e-04,
          1.0238299e-01, -3.8162190e-01,  1.3609882e-01],
        [ 1.1664447e-01,  1.2225841e-01,  9.7429514e-01,  1.4397621e-02,
          3.1768478e-02,  4.1787773e-01,  4.5753318e-01]], dtype=float32),
 array([ 0.22041214,  0.8116048 ,  0.37825504,  1.4114149 , -0.09595512,
         0.40657243, -0.37297344], dtype=float32)]

In [24]:
y_log = model.predict(X_test_scale)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [25]:
y_pred = np.where(y_log>0.5,1,0)

In [26]:
y_pred.shape

(2000, 1)

In [27]:
y_test.shape

(2000,)

In [28]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8675

In [29]:
plt.plot(history.history['loss'])

NameError: name 'plt' is not defined